from sklearn_quantile.ensemble import RandomForestQuantileRegressor, ExtraTreesQuantileRegressor, \
    RandomForestMaximumRegressor
from sklearn_quantile.neighbors import KNeighborsQuantileRegressor
