name: build

on: workflow_call

jobs:  
  build-linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["9", "10", "11", "12"]

    steps:
    - uses: actions/checkout@v2

    - name: Install Python package dependencies
      run: /opt/python/cp3${{ matrix.python-version }}-cp3${{ matrix.python-version }}/bin/python -m pip install cython wheel setuptools numpy>=1.22.3 pytest twine

    - name: Build binary wheel
      run: /opt/python/cp3${{ matrix.python-version }}-cp3${{ matrix.python-version }}/bin/python setup.py bdist_wheel

    - name: Apply auditwheel for manylinux wheel
      run: auditwheel repair -w dist dist/*

    - name: Remove linux wheel
      run: rm dist/*-linux_x86_64.whl

    - name: Install locally
      run: pip install .

    - name: Run tests
      run: pytest

    - name: Test twine
      run: |
        ls -ln 
        twine check --strict dist/*

    - name: Archive dist artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-linux-3.${{ matrix.python-version }}
        path: dist

  build-macos:
    runs-on: macos-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }} x64
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install Python package dependencies
      run: pip install cython wheel setuptools numpy>=1.22.3 pytest twine

    - name: Build binary wheel
      run: python setup.py bdist_wheel

    - name: Install locally
      run: pip install .

    - name: Run tests
      run: pytest

    - name: Test twine
      run: |
        ls -ln 
        twine check --strict dist/*

    - name: Archive dist artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-macos-${{ matrix.python-version }}
        path: dist




  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2

    - name: Download Build Tools for Visual Studio 2019
      run: Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile vs_buildtools.exe

    - name: Run vs_buildtools.exe install
      run: ./vs_buildtools.exe --quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.v141.x86.x64 --add Microsoft.VisualStudio.Component.VC.140 --includeRecommended

    - name: Set up Python ${{ matrix.python-version }} x64
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install Python package dependencies
      run: pip install cython wheel setuptools numpy>=1.22.3 pytest twine

    - name: Build binary wheel
      run: python setup.py bdist_wheel

    - name: Install locally
      run: pip install .

    - name: Run tests
      run: pytest

    - name: Test twine
      run: |
        ls -ln 
        twine check --strict dist/*

    - name: Archive dist artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-windows-${{ matrix.python-version }}
        path: dist
