name: build

on: workflow_call

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13, macos-14 ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup micromamba and install dependencies
        uses: mamba-org/setup-micromamba@v2
        with:
          init-shell: bash
          environment-name: sklearn-quantile-env
          create-args: >-
            python=3.10

      - name: Install cibuildwheel
        shell: bash -l {0}
        run: |
          micromamba activate sklearn-quantile-env
          python -m pip install cibuildwheel

      - name: Build wheels
        shell: bash -l {0}
        run: |
          micromamba activate sklearn-quantile-env
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.10"
          CIBW_SKIP: pp*

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
