name: release

on:
  push:
    tags:  # trigger the deploy job on tag creation
        - v*

jobs:
  push:
    uses: ./.github/workflows/push.yml  # use the callable tests job to run tests
    
  copy:
    runs-on: ubuntu-latest
    name: release
    needs: [push]
    strategy:
        max-parallel: 1
        matrix:
          python-version: ["3.8", "3.9", "3.10", "3.11"]
          os: ['windows', 'linux', 'macos']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython wheel setuptools numpy>=1.22.3

    - name: Create source dist
      run: python setup.py sdist

    - name: Stage ${{ matrix.os }} ${{ matrix.python-version }}
      uses: actions/download-artifact@v2
      with:
        name: dist-${{ matrix.os }}-${{ matrix.python-version }}
    - run: mv -v dist-${{ matrix.os }}-${{ matrix.python-version }}/* dist/

  upload:
    runs-on: ubuntu-latest
    name: release
    needs: [copy]
    
    steps:
      
    - name: Upload
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        ls -l dist/*
        pip install twine
        twine upload dist/*
