name: release

on:
  push:
    tags: # trigger the deploy job on tag creation
      - v*
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/test.yml

  build:
    name: Build wheels
    uses: ./.github/workflows/build.yml

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload_pypi:
    name: Release
    needs: [ test, build, build_sdist ]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/sklearn-quantile
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
