name: release

on:
  push:
    tags:  # trigger the deploy job on tag creation
        - v*
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml  # use the callable tests job to run tests

  sdist:
    name: sdist
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython wheel setuptools numpy>=1.22.3
  
      - name: Create source dist
        run: python setup.py sdist

      - name: Archive dist
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist

  copy:
    runs-on: ubuntu-latest
    name: release
    needs: [build]
    strategy:
        max-parallel: 5
        matrix:
          python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
          os: ['windows', 'linux', 'macos']

    steps:
    - name: Create output folder
      uses: actions/checkout@v2
    - run: mkdir dist

    - name: Load sdist
      uses: actions/download-artifact@v2
      with:
        name: sdist
    - run: mv -v *.tar.gz dist/

    - name: Stage ${{ matrix.os }} ${{ matrix.python-version }}
      uses: actions/download-artifact@v2
      with:
        name: dist-${{ matrix.os }}-${{ matrix.python-version }}
    - run: mv -v *.whl dist/

    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./

  upload:
    runs-on: ubuntu-latest
    name: release
    needs: [copy, sdist]
    
    steps:
    
    - name: Load
      uses: actions/download-artifact@v2
      with:
        name: dist

    - name: Install dependencies
      run: pip install twine

    - name: Twine check
      run: twine check --strict dist/*

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
